# Generated by Django 2.2 on 2021-05-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='photo',
            field=models.URLField(default=123),
            preserve_default=False,
        ),
    ]
